s3 draft
Skatteetaten/openshift-reference-springboot-server-kotlin pull request #15
Opened 2020-10-13 08:58 UTC by kris456

2020-10-16 11:06 UTC, bentsolheim requested changes

2020-10-16 11:06 UTC, bentsolheim commented on pom.xml
> +      <groupId>org.postgresql</groupId>
Lurer på om vi bør ha et Beslutningsdokument på å endre fra Oracle til Postgres?

2020-10-16 11:06 UTC, bentsolheim commented on docker-compose.yaml
> +version: "3.7"
Tror vi bør ha et beslutningsdokument på at introduserer docker-compose.

2020-10-16 12:54 UTC, kris456 commented on src/main/kotlin/no/skatteetaten/aurora/openshift/reference/springboot/service/S3Service.kt
> +        putHostFile()
tatt bort :)

2020-10-16 12:55 UTC, kris456 commented on src/main/resources/application.yml
> +        driver-class-name: org.postgresql.Driver
Det viste seg at den ikke var nødvendig, takk

2020-10-16 12:55 UTC, kris456 commented on pom.xml
> +      <groupId>org.postgresql</groupId>
Dokument laget

2020-10-16 12:55 UTC, kris456 commented on docker-compose.yaml
> +version: "3.7"
Dokument har blit laget

2020-10-16 21:04 UTC, Aerlant approved these changes

2020-10-21 11:40 UTC, kris456 commented on src/test/kotlin/no/skatteetaten/aurora/openshift/reference/springboot/service/S3ServiceTest.kt
> +@SpringBootTest
Tar gjerne imot forslag på en måte å ikke dra inn alt her, men fortsatt kunne bruke application.yml i test resources og applicationConfig

2020-10-22 06:47 UTC, bjartek requested changes

2020-10-22 06:47 UTC, bjartek commented on pom.xml
> +      <version>2.15.7</version>
Trekke denne ut som en property.

2020-10-22 06:47 UTC, bjartek commented on pom.xml
> +      <version>0.2.6</version>
trekke denne ut som en property

2020-10-22 06:47 UTC, bjartek commented on pom.xml
> +      <version>1.5.5</version>
trekke denne ut som en property

2020-10-22 06:47 UTC, bjartek commented on src/main/kotlin/no/skatteetaten/aurora/openshift/reference/springboot/service/S3Service.kt
> +            RequestBody.fromFile(file)
Bruk RequestBody.fromSting og send inn innholdet.

2020-10-22 07:42 UTC, bentsolheim approved these changes

2020-11-23 09:16 UTC, bjartek approved these changes

2020-11-23 13:30 UTC, merged